services:
  api2:
    image: ghcr.io/Waltgt/sistema-ecommerce-backend:latest
    container_name: api2
    restart: unless-stopped
    env_file:
      - ./backend.env
    environment:
      - INSTANCE_NAME=api2
    ports:
      - "3000:3000"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    driver: bridge