name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Actualizar codigo en server-api
        run: |
          cd ~/e-commerce
          git pull origin main
          cd backend
          npm ci
          npx prisma generate
          npm run build

      - name: Reiniciar api1 en server-api
        run: |
          cd ~/e-commerce/backend
          pm2 reload api-backend --update-env

      - name: Actualizar codigo en server-api2
        run: |
          ssh 10.0.2.9 "cd ~/e-commerce/backend && git pull origin main && npm ci && npx prisma generate && npm run build && pm2 reload api-backend --update-env"